#############################################################################
# Makefile for building: build/bin/game_menu
# Generated by qmake (3.1) (Qt 6.8.2)
# Project:  game_menu.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile game_menu.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = @echo compiling $< && gcc
CXX           = @echo compiling $< && g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++2a -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -Ibuild/moc -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = game_menu1.0.0
DISTDIR = /home/rickard/Documents/GitHub/depthofdejenol/build/obj/release/game_menu1.0.0
LINK          = @echo linking $@ && g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Multimedia.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Network.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/release/

####### Files

SOURCES       = GameStateManager.cpp \
		game_menu.cpp \
		TheCity.cpp \
		tools/monster_editor/MonsterEditorDialog.cpp \
		tools/spellbook_editor/SpellbookEditorDialog.cpp \
		src/network_manager/NetworkManager.cpp \
		src/hall_of_records/hallofrecordsdialog.cpp \
		src/create_character/createcharacterdialog.cpp \
		src/about_dialog/AboutDialog.cpp \
		src/character_dialog/CharacterDialog.cpp \
		src/message_window/MessageWindow.cpp \
		src/sender_window/SenderWindow.cpp \
		src/library_dialog/library_dialog.cpp \
		src/automap/automap_dialog.cpp \
		src/game_controller/game_controller.cpp \
		src/characterlist_dialog/characterlistdialog.cpp \
		src/helplesson/helplesson.cpp \
		src/mordorstatistics/mordorstatistics.cpp \
		src/loadingscreen/LoadingScreen.cpp \
		src/guilds_dialog/GuildsDialog.cpp \
		src/general_store/GeneralStore.cpp \
		src/morgue_dialog/MorgueDialog.cpp \
		src/seer_dialog/SeerDialog.cpp \
		src/confinement_dialog/ConfinementDialog.cpp \
		src/bank_dialog/BankDialog.cpp \
		src/race_data/RaceData.cpp \
		src/inventory_dialog/inventorydialog.cpp \
		src/options_dialog/optionsdialog.cpp \
		src/dungeon_dialog/DungeonDialog.cpp \
		src/partyinfo_dialog/partyinfodialog.cpp \
		src/dungeonmap/dungeonmap.cpp \
		src/bank_dialog/TradeDialog.cpp \
		src/game_resources.cpp \
		src/dungeon_dialog/DungeonMinimap.cpp \
		src/dungeon_dialog/DungeonHandlers.cpp \
		src/event/EventManager.cpp \
		src/update/UpdateManager.cpp \
		src/update/UpdateDialog.cpp \
		src/spell_casting/SpellCastingDialog.cpp build/moc/moc_GameStateManager.cpp \
		build/moc/moc_game_menu.cpp \
		build/moc/moc_TheCity.cpp \
		build/moc/moc_StoryDialog.cpp \
		build/moc/moc_MonsterEditorDialog.cpp \
		build/moc/moc_SpellbookEditorDialog.cpp \
		build/moc/moc_NetworkManager.cpp \
		build/moc/moc_hallofrecordsdialog.cpp \
		build/moc/moc_createcharacterdialog.cpp \
		build/moc/moc_AboutDialog.cpp \
		build/moc/moc_CharacterDialog.cpp \
		build/moc/moc_MessageWindow.cpp \
		build/moc/moc_SenderWindow.cpp \
		build/moc/moc_library_dialog.cpp \
		build/moc/moc_automap_dialog.cpp \
		build/moc/moc_game_controller.cpp \
		build/moc/moc_characterlistdialog.cpp \
		build/moc/moc_helplesson.cpp \
		build/moc/moc_mordorstatistics.cpp \
		build/moc/moc_LoadingScreen.cpp \
		build/moc/moc_GuildsDialog.cpp \
		build/moc/moc_GeneralStore.cpp \
		build/moc/moc_MorgueDialog.cpp \
		build/moc/moc_SeerDialog.cpp \
		build/moc/moc_ConfinementDialog.cpp \
		build/moc/moc_BankDialog.cpp \
		build/moc/moc_inventorydialog.cpp \
		build/moc/moc_optionsdialog.cpp \
		build/moc/moc_DungeonDialog.cpp \
		build/moc/moc_partyinfodialog.cpp \
		build/moc/moc_dungeonmap.cpp \
		build/moc/moc_TradeDialog.cpp \
		build/moc/moc_EventManager.cpp \
		build/moc/moc_MiniMapDialog.cpp \
		build/moc/moc_UpdateManager.cpp \
		build/moc/moc_UpdateDialog.cpp \
		build/moc/moc_SpellCastingDialog.cpp
OBJECTS       = build/obj/release/GameStateManager.o \
		build/obj/release/game_menu.o \
		build/obj/release/TheCity.o \
		build/obj/release/MonsterEditorDialog.o \
		build/obj/release/SpellbookEditorDialog.o \
		build/obj/release/NetworkManager.o \
		build/obj/release/hallofrecordsdialog.o \
		build/obj/release/createcharacterdialog.o \
		build/obj/release/AboutDialog.o \
		build/obj/release/CharacterDialog.o \
		build/obj/release/MessageWindow.o \
		build/obj/release/SenderWindow.o \
		build/obj/release/library_dialog.o \
		build/obj/release/automap_dialog.o \
		build/obj/release/game_controller.o \
		build/obj/release/characterlistdialog.o \
		build/obj/release/helplesson.o \
		build/obj/release/mordorstatistics.o \
		build/obj/release/LoadingScreen.o \
		build/obj/release/GuildsDialog.o \
		build/obj/release/GeneralStore.o \
		build/obj/release/MorgueDialog.o \
		build/obj/release/SeerDialog.o \
		build/obj/release/ConfinementDialog.o \
		build/obj/release/BankDialog.o \
		build/obj/release/RaceData.o \
		build/obj/release/inventorydialog.o \
		build/obj/release/optionsdialog.o \
		build/obj/release/DungeonDialog.o \
		build/obj/release/partyinfodialog.o \
		build/obj/release/dungeonmap.o \
		build/obj/release/TradeDialog.o \
		build/obj/release/game_resources.o \
		build/obj/release/DungeonMinimap.o \
		build/obj/release/DungeonHandlers.o \
		build/obj/release/EventManager.o \
		build/obj/release/UpdateManager.o \
		build/obj/release/UpdateDialog.o \
		build/obj/release/SpellCastingDialog.o \
		build/obj/release/moc_GameStateManager.o \
		build/obj/release/moc_game_menu.o \
		build/obj/release/moc_TheCity.o \
		build/obj/release/moc_StoryDialog.o \
		build/obj/release/moc_MonsterEditorDialog.o \
		build/obj/release/moc_SpellbookEditorDialog.o \
		build/obj/release/moc_NetworkManager.o \
		build/obj/release/moc_hallofrecordsdialog.o \
		build/obj/release/moc_createcharacterdialog.o \
		build/obj/release/moc_AboutDialog.o \
		build/obj/release/moc_CharacterDialog.o \
		build/obj/release/moc_MessageWindow.o \
		build/obj/release/moc_SenderWindow.o \
		build/obj/release/moc_library_dialog.o \
		build/obj/release/moc_automap_dialog.o \
		build/obj/release/moc_game_controller.o \
		build/obj/release/moc_characterlistdialog.o \
		build/obj/release/moc_helplesson.o \
		build/obj/release/moc_mordorstatistics.o \
		build/obj/release/moc_LoadingScreen.o \
		build/obj/release/moc_GuildsDialog.o \
		build/obj/release/moc_GeneralStore.o \
		build/obj/release/moc_MorgueDialog.o \
		build/obj/release/moc_SeerDialog.o \
		build/obj/release/moc_ConfinementDialog.o \
		build/obj/release/moc_BankDialog.o \
		build/obj/release/moc_inventorydialog.o \
		build/obj/release/moc_optionsdialog.o \
		build/obj/release/moc_DungeonDialog.o \
		build/obj/release/moc_partyinfodialog.o \
		build/obj/release/moc_dungeonmap.o \
		build/obj/release/moc_TradeDialog.o \
		build/obj/release/moc_EventManager.o \
		build/obj/release/moc_MiniMapDialog.o \
		build/obj/release/moc_UpdateManager.o \
		build/obj/release/moc_UpdateDialog.o \
		build/obj/release/moc_SpellCastingDialog.o
DIST          = .gitignore \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/permissions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/silent.prf \
		game_menu.pro include/GameConstants.h \
		GameStateManager.h \
		game_menu.h \
		TheCity.h \
		StoryDialog.h \
		tools/monster_editor/MonsterEditorDialog.h \
		tools/spellbook_editor/SpellbookEditorDialog.h \
		src/network_manager/NetworkManager.h \
		src/hall_of_records/hallofrecordsdialog.h \
		src/create_character/createcharacterdialog.h \
		src/about_dialog/AboutDialog.h \
		src/character_dialog/CharacterDialog.h \
		src/message_window/MessageWindow.h \
		src/sender_window/SenderWindow.h \
		src/library_dialog/library_dialog.h \
		src/automap/automap_dialog.h \
		src/game_controller/game_controller.h \
		src/characterlist_dialog/characterlistdialog.h \
		src/helplesson/helplesson.h \
		src/mordorstatistics/mordorstatistics.h \
		src/loadingscreen/LoadingScreen.h \
		src/guilds_dialog/GuildsDialog.h \
		src/general_store/GeneralStore.h \
		src/morgue_dialog/MorgueDialog.h \
		src/seer_dialog/SeerDialog.h \
		src/confinement_dialog/ConfinementDialog.h \
		src/bank_dialog/BankDialog.h \
		src/race_data/RaceData.h \
		src/inventory_dialog/inventorydialog.h \
		src/options_dialog/optionsdialog.h \
		src/dungeon_dialog/DungeonDialog.h \
		src/partyinfo_dialog/partyinfodialog.h \
		src/dungeonmap/dungeonmap.h \
		src/bank_dialog/TradeDialog.h \
		include/game_resources.h \
		src/dungeon_dialog/DungeonHandlers.h \
		src/event/EventManager.h \
		src/dungeon_dialog/MiniMapDialog.h \
		src/update/UpdateManager.h \
		src/update/UpdateDialog.h \
		src/spell_casting/SpellCastingDialog.h GameStateManager.cpp \
		game_menu.cpp \
		TheCity.cpp \
		tools/monster_editor/MonsterEditorDialog.cpp \
		tools/spellbook_editor/SpellbookEditorDialog.cpp \
		src/network_manager/NetworkManager.cpp \
		src/hall_of_records/hallofrecordsdialog.cpp \
		src/create_character/createcharacterdialog.cpp \
		src/about_dialog/AboutDialog.cpp \
		src/character_dialog/CharacterDialog.cpp \
		src/message_window/MessageWindow.cpp \
		src/sender_window/SenderWindow.cpp \
		src/library_dialog/library_dialog.cpp \
		src/automap/automap_dialog.cpp \
		src/game_controller/game_controller.cpp \
		src/characterlist_dialog/characterlistdialog.cpp \
		src/helplesson/helplesson.cpp \
		src/mordorstatistics/mordorstatistics.cpp \
		src/loadingscreen/LoadingScreen.cpp \
		src/guilds_dialog/GuildsDialog.cpp \
		src/general_store/GeneralStore.cpp \
		src/morgue_dialog/MorgueDialog.cpp \
		src/seer_dialog/SeerDialog.cpp \
		src/confinement_dialog/ConfinementDialog.cpp \
		src/bank_dialog/BankDialog.cpp \
		src/race_data/RaceData.cpp \
		src/inventory_dialog/inventorydialog.cpp \
		src/options_dialog/optionsdialog.cpp \
		src/dungeon_dialog/DungeonDialog.cpp \
		src/partyinfo_dialog/partyinfodialog.cpp \
		src/dungeonmap/dungeonmap.cpp \
		src/bank_dialog/TradeDialog.cpp \
		src/game_resources.cpp \
		src/dungeon_dialog/DungeonMinimap.cpp \
		src/dungeon_dialog/DungeonHandlers.cpp \
		src/event/EventManager.cpp \
		src/update/UpdateManager.cpp \
		src/update/UpdateDialog.cpp \
		src/spell_casting/SpellCastingDialog.cpp
QMAKE_TARGET  = game_menu
DESTDIR       = build/bin/
TARGET        = build/bin/game_menu


first: all
####### Build rules

build/bin/game_menu:  $(OBJECTS)  
	@test -d build/bin/ || mkdir -p build/bin/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)
	
	 $(COPY_DIR) /home/rickard/Documents/GitHub/depthofdejenol/data build/bin 
	 $(COPY_FILE) build/bin/game_menu /home/rickard/Documents/GitHub/depthofdejenol/game_menu

Makefile: game_menu.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/permissions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/silent.prf \
		game_menu.pro \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile game_menu.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/permissions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/silent.prf:
game_menu.pro:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Network.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile game_menu.pro

qmake_all: FORCE


all: Makefile build/bin/game_menu

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/GameConstants.h GameStateManager.h game_menu.h TheCity.h StoryDialog.h tools/monster_editor/MonsterEditorDialog.h tools/spellbook_editor/SpellbookEditorDialog.h src/network_manager/NetworkManager.h src/hall_of_records/hallofrecordsdialog.h src/create_character/createcharacterdialog.h src/about_dialog/AboutDialog.h src/character_dialog/CharacterDialog.h src/message_window/MessageWindow.h src/sender_window/SenderWindow.h src/library_dialog/library_dialog.h src/automap/automap_dialog.h src/game_controller/game_controller.h src/characterlist_dialog/characterlistdialog.h src/helplesson/helplesson.h src/mordorstatistics/mordorstatistics.h src/loadingscreen/LoadingScreen.h src/guilds_dialog/GuildsDialog.h src/general_store/GeneralStore.h src/morgue_dialog/MorgueDialog.h src/seer_dialog/SeerDialog.h src/confinement_dialog/ConfinementDialog.h src/bank_dialog/BankDialog.h src/race_data/RaceData.h src/inventory_dialog/inventorydialog.h src/options_dialog/optionsdialog.h src/dungeon_dialog/DungeonDialog.h src/partyinfo_dialog/partyinfodialog.h src/dungeonmap/dungeonmap.h src/bank_dialog/TradeDialog.h include/game_resources.h src/dungeon_dialog/DungeonHandlers.h src/event/EventManager.h src/dungeon_dialog/MiniMapDialog.h src/update/UpdateManager.h src/update/UpdateDialog.h src/spell_casting/SpellCastingDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents GameStateManager.cpp game_menu.cpp TheCity.cpp tools/monster_editor/MonsterEditorDialog.cpp tools/spellbook_editor/SpellbookEditorDialog.cpp src/network_manager/NetworkManager.cpp src/hall_of_records/hallofrecordsdialog.cpp src/create_character/createcharacterdialog.cpp src/about_dialog/AboutDialog.cpp src/character_dialog/CharacterDialog.cpp src/message_window/MessageWindow.cpp src/sender_window/SenderWindow.cpp src/library_dialog/library_dialog.cpp src/automap/automap_dialog.cpp src/game_controller/game_controller.cpp src/characterlist_dialog/characterlistdialog.cpp src/helplesson/helplesson.cpp src/mordorstatistics/mordorstatistics.cpp src/loadingscreen/LoadingScreen.cpp src/guilds_dialog/GuildsDialog.cpp src/general_store/GeneralStore.cpp src/morgue_dialog/MorgueDialog.cpp src/seer_dialog/SeerDialog.cpp src/confinement_dialog/ConfinementDialog.cpp src/bank_dialog/BankDialog.cpp src/race_data/RaceData.cpp src/inventory_dialog/inventorydialog.cpp src/options_dialog/optionsdialog.cpp src/dungeon_dialog/DungeonDialog.cpp src/partyinfo_dialog/partyinfodialog.cpp src/dungeonmap/dungeonmap.cpp src/bank_dialog/TradeDialog.cpp src/game_resources.cpp src/dungeon_dialog/DungeonMinimap.cpp src/dungeon_dialog/DungeonHandlers.cpp src/event/EventManager.cpp src/update/UpdateManager.cpp src/update/UpdateDialog.cpp src/spell_casting/SpellCastingDialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	@echo generating build/moc/moc_predefs.h
	@g++ -pipe -O2 -std=gnu++2a -Wall -Wextra -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_GameStateManager.cpp build/moc/moc_game_menu.cpp build/moc/moc_TheCity.cpp build/moc/moc_StoryDialog.cpp build/moc/moc_MonsterEditorDialog.cpp build/moc/moc_SpellbookEditorDialog.cpp build/moc/moc_NetworkManager.cpp build/moc/moc_hallofrecordsdialog.cpp build/moc/moc_createcharacterdialog.cpp build/moc/moc_AboutDialog.cpp build/moc/moc_CharacterDialog.cpp build/moc/moc_MessageWindow.cpp build/moc/moc_SenderWindow.cpp build/moc/moc_library_dialog.cpp build/moc/moc_automap_dialog.cpp build/moc/moc_game_controller.cpp build/moc/moc_characterlistdialog.cpp build/moc/moc_helplesson.cpp build/moc/moc_mordorstatistics.cpp build/moc/moc_LoadingScreen.cpp build/moc/moc_GuildsDialog.cpp build/moc/moc_GeneralStore.cpp build/moc/moc_MorgueDialog.cpp build/moc/moc_SeerDialog.cpp build/moc/moc_ConfinementDialog.cpp build/moc/moc_BankDialog.cpp build/moc/moc_inventorydialog.cpp build/moc/moc_optionsdialog.cpp build/moc/moc_DungeonDialog.cpp build/moc/moc_partyinfodialog.cpp build/moc/moc_dungeonmap.cpp build/moc/moc_TradeDialog.cpp build/moc/moc_EventManager.cpp build/moc/moc_MiniMapDialog.cpp build/moc/moc_UpdateManager.cpp build/moc/moc_UpdateDialog.cpp build/moc/moc_SpellCastingDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_GameStateManager.cpp build/moc/moc_game_menu.cpp build/moc/moc_TheCity.cpp build/moc/moc_StoryDialog.cpp build/moc/moc_MonsterEditorDialog.cpp build/moc/moc_SpellbookEditorDialog.cpp build/moc/moc_NetworkManager.cpp build/moc/moc_hallofrecordsdialog.cpp build/moc/moc_createcharacterdialog.cpp build/moc/moc_AboutDialog.cpp build/moc/moc_CharacterDialog.cpp build/moc/moc_MessageWindow.cpp build/moc/moc_SenderWindow.cpp build/moc/moc_library_dialog.cpp build/moc/moc_automap_dialog.cpp build/moc/moc_game_controller.cpp build/moc/moc_characterlistdialog.cpp build/moc/moc_helplesson.cpp build/moc/moc_mordorstatistics.cpp build/moc/moc_LoadingScreen.cpp build/moc/moc_GuildsDialog.cpp build/moc/moc_GeneralStore.cpp build/moc/moc_MorgueDialog.cpp build/moc/moc_SeerDialog.cpp build/moc/moc_ConfinementDialog.cpp build/moc/moc_BankDialog.cpp build/moc/moc_inventorydialog.cpp build/moc/moc_optionsdialog.cpp build/moc/moc_DungeonDialog.cpp build/moc/moc_partyinfodialog.cpp build/moc/moc_dungeonmap.cpp build/moc/moc_TradeDialog.cpp build/moc/moc_EventManager.cpp build/moc/moc_MiniMapDialog.cpp build/moc/moc_UpdateManager.cpp build/moc/moc_UpdateDialog.cpp build/moc/moc_SpellCastingDialog.cpp
build/moc/moc_GameStateManager.cpp: GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc GameStateManager.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include GameStateManager.h -o build/moc/moc_GameStateManager.cpp

build/moc/moc_game_menu.cpp: game_menu.h \
		src/event/EventManager.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc game_menu.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include game_menu.h -o build/moc/moc_game_menu.cpp

build/moc/moc_TheCity.cpp: TheCity.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc TheCity.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include TheCity.h -o build/moc/moc_TheCity.cpp

build/moc/moc_StoryDialog.cpp: StoryDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc StoryDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include StoryDialog.h -o build/moc/moc_StoryDialog.cpp

build/moc/moc_MonsterEditorDialog.cpp: tools/monster_editor/MonsterEditorDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc tools/monster_editor/MonsterEditorDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tools/monster_editor/MonsterEditorDialog.h -o build/moc/moc_MonsterEditorDialog.cpp

build/moc/moc_SpellbookEditorDialog.cpp: tools/spellbook_editor/SpellbookEditorDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc tools/spellbook_editor/SpellbookEditorDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tools/spellbook_editor/SpellbookEditorDialog.h -o build/moc/moc_SpellbookEditorDialog.cpp

build/moc/moc_NetworkManager.cpp: src/network_manager/NetworkManager.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/network_manager/NetworkManager.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/network_manager/NetworkManager.h -o build/moc/moc_NetworkManager.cpp

build/moc/moc_hallofrecordsdialog.cpp: src/hall_of_records/hallofrecordsdialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/hall_of_records/hallofrecordsdialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/hall_of_records/hallofrecordsdialog.h -o build/moc/moc_hallofrecordsdialog.cpp

build/moc/moc_createcharacterdialog.cpp: src/create_character/createcharacterdialog.h \
		src/race_data/RaceData.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/create_character/createcharacterdialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/create_character/createcharacterdialog.h -o build/moc/moc_createcharacterdialog.cpp

build/moc/moc_AboutDialog.cpp: src/about_dialog/AboutDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/about_dialog/AboutDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/about_dialog/AboutDialog.h -o build/moc/moc_AboutDialog.cpp

build/moc/moc_CharacterDialog.cpp: src/character_dialog/CharacterDialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/character_dialog/CharacterDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/character_dialog/CharacterDialog.h -o build/moc/moc_CharacterDialog.cpp

build/moc/moc_MessageWindow.cpp: src/message_window/MessageWindow.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/message_window/MessageWindow.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/message_window/MessageWindow.h -o build/moc/moc_MessageWindow.cpp

build/moc/moc_SenderWindow.cpp: src/sender_window/SenderWindow.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/sender_window/SenderWindow.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/sender_window/SenderWindow.h -o build/moc/moc_SenderWindow.cpp

build/moc/moc_library_dialog.cpp: src/library_dialog/library_dialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/library_dialog/library_dialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/library_dialog/library_dialog.h -o build/moc/moc_library_dialog.cpp

build/moc/moc_automap_dialog.cpp: src/automap/automap_dialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/automap/automap_dialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/automap/automap_dialog.h -o build/moc/moc_automap_dialog.cpp

build/moc/moc_game_controller.cpp: src/game_controller/game_controller.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/game_controller/game_controller.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/game_controller/game_controller.h -o build/moc/moc_game_controller.cpp

build/moc/moc_characterlistdialog.cpp: src/characterlist_dialog/characterlistdialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/characterlist_dialog/characterlistdialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/characterlist_dialog/characterlistdialog.h -o build/moc/moc_characterlistdialog.cpp

build/moc/moc_helplesson.cpp: src/helplesson/helplesson.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/helplesson/helplesson.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/helplesson/helplesson.h -o build/moc/moc_helplesson.cpp

build/moc/moc_mordorstatistics.cpp: src/mordorstatistics/mordorstatistics.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/mordorstatistics/mordorstatistics.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mordorstatistics/mordorstatistics.h -o build/moc/moc_mordorstatistics.cpp

build/moc/moc_LoadingScreen.cpp: src/loadingscreen/LoadingScreen.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/loadingscreen/LoadingScreen.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/loadingscreen/LoadingScreen.h -o build/moc/moc_LoadingScreen.cpp

build/moc/moc_GuildsDialog.cpp: src/guilds_dialog/GuildsDialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/guilds_dialog/GuildsDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/guilds_dialog/GuildsDialog.h -o build/moc/moc_GuildsDialog.cpp

build/moc/moc_GeneralStore.cpp: src/general_store/GeneralStore.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/general_store/GeneralStore.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/general_store/GeneralStore.h -o build/moc/moc_GeneralStore.cpp

build/moc/moc_MorgueDialog.cpp: src/morgue_dialog/MorgueDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/morgue_dialog/MorgueDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/morgue_dialog/MorgueDialog.h -o build/moc/moc_MorgueDialog.cpp

build/moc/moc_SeerDialog.cpp: src/seer_dialog/SeerDialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/seer_dialog/SeerDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/seer_dialog/SeerDialog.h -o build/moc/moc_SeerDialog.cpp

build/moc/moc_ConfinementDialog.cpp: src/confinement_dialog/ConfinementDialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/confinement_dialog/ConfinementDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/confinement_dialog/ConfinementDialog.h -o build/moc/moc_ConfinementDialog.cpp

build/moc/moc_BankDialog.cpp: src/bank_dialog/BankDialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/bank_dialog/BankDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/bank_dialog/BankDialog.h -o build/moc/moc_BankDialog.cpp

build/moc/moc_inventorydialog.cpp: src/inventory_dialog/inventorydialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/inventory_dialog/inventorydialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/inventory_dialog/inventorydialog.h -o build/moc/moc_inventorydialog.cpp

build/moc/moc_optionsdialog.cpp: src/options_dialog/optionsdialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/options_dialog/optionsdialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/options_dialog/optionsdialog.h -o build/moc/moc_optionsdialog.cpp

build/moc/moc_DungeonDialog.cpp: src/dungeon_dialog/DungeonDialog.h \
		src/inventory_dialog/inventorydialog.h \
		GameStateManager.h \
		character.h \
		src/partyinfo_dialog/partyinfodialog.h \
		src/event/EventManager.h \
		src/dungeon_dialog/MiniMapDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/dungeon_dialog/DungeonDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dungeon_dialog/DungeonDialog.h -o build/moc/moc_DungeonDialog.cpp

build/moc/moc_partyinfodialog.cpp: src/partyinfo_dialog/partyinfodialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/partyinfo_dialog/partyinfodialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/partyinfo_dialog/partyinfodialog.h -o build/moc/moc_partyinfodialog.cpp

build/moc/moc_dungeonmap.cpp: src/dungeonmap/dungeonmap.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/dungeonmap/dungeonmap.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dungeonmap/dungeonmap.h -o build/moc/moc_dungeonmap.cpp

build/moc/moc_TradeDialog.cpp: src/bank_dialog/TradeDialog.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/bank_dialog/TradeDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/bank_dialog/TradeDialog.h -o build/moc/moc_TradeDialog.cpp

build/moc/moc_EventManager.cpp: src/event/EventManager.h \
		GameStateManager.h \
		character.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/event/EventManager.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/event/EventManager.h -o build/moc/moc_EventManager.cpp

build/moc/moc_MiniMapDialog.cpp: src/dungeon_dialog/MiniMapDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/dungeon_dialog/MiniMapDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dungeon_dialog/MiniMapDialog.h -o build/moc/moc_MiniMapDialog.cpp

build/moc/moc_UpdateManager.cpp: src/update/UpdateManager.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/update/UpdateManager.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/update/UpdateManager.h -o build/moc/moc_UpdateManager.cpp

build/moc/moc_UpdateDialog.cpp: src/update/UpdateDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/update/UpdateDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/update/UpdateDialog.h -o build/moc/moc_UpdateDialog.cpp

build/moc/moc_SpellCastingDialog.cpp: src/spell_casting/SpellCastingDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	@echo moc src/spell_casting/SpellCastingDialog.h && /usr/lib/qt6/libexec/moc $(DEFINES) --include /home/rickard/Documents/GitHub/depthofdejenol/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/rickard/Documents/GitHub/depthofdejenol -I/home/rickard/Documents/GitHub/depthofdejenol/_PRO_FILE_PWD_/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/x86_64-linux-gnu/c++/15 -I/usr/include/c++/15/backward -I/usr/lib/gcc/x86_64-linux-gnu/15/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/spell_casting/SpellCastingDialog.h -o build/moc/moc_SpellCastingDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/release/GameStateManager.o: GameStateManager.cpp GameStateManager.h \
		character.h \
		src/race_data/RaceData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/GameStateManager.o GameStateManager.cpp

build/obj/release/game_menu.o: game_menu.cpp GameStateManager.h \
		character.h \
		game_menu.h \
		src/event/EventManager.h \
		TheCity.h \
		StoryDialog.h \
		tools/spellbook_editor/SpellbookEditorDialog.h \
		tools/monster_editor/MonsterEditorDialog.h \
		src/characterlist_dialog/characterlistdialog.h \
		src/hall_of_records/hallofrecordsdialog.h \
		src/create_character/createcharacterdialog.h \
		src/race_data/RaceData.h \
		src/inventory_dialog/inventorydialog.h \
		src/options_dialog/optionsdialog.h \
		src/about_dialog/AboutDialog.h \
		src/character_dialog/CharacterDialog.h \
		src/message_window/MessageWindow.h \
		src/sender_window/SenderWindow.h \
		src/library_dialog/library_dialog.h \
		src/automap/automap_dialog.h \
		src/game_controller/game_controller.h \
		src/helplesson/helplesson.h \
		src/mordorstatistics/mordorstatistics.h \
		src/loadingscreen/LoadingScreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/game_menu.o game_menu.cpp

build/obj/release/TheCity.o: TheCity.cpp TheCity.h \
		include/game_resources.h \
		src/network_manager/NetworkManager.h \
		src/partyinfo_dialog/partyinfodialog.h \
		src/general_store/GeneralStore.h \
		GameStateManager.h \
		character.h \
		src/guilds_dialog/GuildsDialog.h \
		src/morgue_dialog/MorgueDialog.h \
		src/seer_dialog/SeerDialog.h \
		src/confinement_dialog/ConfinementDialog.h \
		src/bank_dialog/BankDialog.h \
		src/dungeon_dialog/DungeonDialog.h \
		src/inventory_dialog/inventorydialog.h \
		src/event/EventManager.h \
		src/dungeon_dialog/MiniMapDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/TheCity.o TheCity.cpp

build/obj/release/MonsterEditorDialog.o: tools/monster_editor/MonsterEditorDialog.cpp tools/monster_editor/MonsterEditorDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/MonsterEditorDialog.o tools/monster_editor/MonsterEditorDialog.cpp

build/obj/release/SpellbookEditorDialog.o: tools/spellbook_editor/SpellbookEditorDialog.cpp tools/spellbook_editor/SpellbookEditorDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/SpellbookEditorDialog.o tools/spellbook_editor/SpellbookEditorDialog.cpp

build/obj/release/NetworkManager.o: src/network_manager/NetworkManager.cpp src/network_manager/NetworkManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/NetworkManager.o src/network_manager/NetworkManager.cpp

build/obj/release/hallofrecordsdialog.o: src/hall_of_records/hallofrecordsdialog.cpp src/hall_of_records/hallofrecordsdialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/hallofrecordsdialog.o src/hall_of_records/hallofrecordsdialog.cpp

build/obj/release/createcharacterdialog.o: src/create_character/createcharacterdialog.cpp src/create_character/createcharacterdialog.h \
		src/race_data/RaceData.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/createcharacterdialog.o src/create_character/createcharacterdialog.cpp

build/obj/release/AboutDialog.o: src/about_dialog/AboutDialog.cpp src/about_dialog/AboutDialog.h \
		GameStateManager.h \
		character.h \
		src/update/UpdateDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/AboutDialog.o src/about_dialog/AboutDialog.cpp

build/obj/release/CharacterDialog.o: src/character_dialog/CharacterDialog.cpp src/character_dialog/CharacterDialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/CharacterDialog.o src/character_dialog/CharacterDialog.cpp

build/obj/release/MessageWindow.o: src/message_window/MessageWindow.cpp src/message_window/MessageWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/MessageWindow.o src/message_window/MessageWindow.cpp

build/obj/release/SenderWindow.o: src/sender_window/SenderWindow.cpp src/sender_window/SenderWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/SenderWindow.o src/sender_window/SenderWindow.cpp

build/obj/release/library_dialog.o: src/library_dialog/library_dialog.cpp src/library_dialog/library_dialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/library_dialog.o src/library_dialog/library_dialog.cpp

build/obj/release/automap_dialog.o: src/automap/automap_dialog.cpp src/automap/automap_dialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/automap_dialog.o src/automap/automap_dialog.cpp

build/obj/release/game_controller.o: src/game_controller/game_controller.cpp src/game_controller/game_controller.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/game_controller.o src/game_controller/game_controller.cpp

build/obj/release/characterlistdialog.o: src/characterlist_dialog/characterlistdialog.cpp src/characterlist_dialog/characterlistdialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/characterlistdialog.o src/characterlist_dialog/characterlistdialog.cpp

build/obj/release/helplesson.o: src/helplesson/helplesson.cpp src/helplesson/helplesson.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/helplesson.o src/helplesson/helplesson.cpp

build/obj/release/mordorstatistics.o: src/mordorstatistics/mordorstatistics.cpp src/mordorstatistics/mordorstatistics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/mordorstatistics.o src/mordorstatistics/mordorstatistics.cpp

build/obj/release/LoadingScreen.o: src/loadingscreen/LoadingScreen.cpp include/game_resources.h \
		src/loadingscreen/LoadingScreen.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/LoadingScreen.o src/loadingscreen/LoadingScreen.cpp

build/obj/release/GuildsDialog.o: src/guilds_dialog/GuildsDialog.cpp src/guilds_dialog/GuildsDialog.h \
		GameStateManager.h \
		character.h \
		src/library_dialog/library_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/GuildsDialog.o src/guilds_dialog/GuildsDialog.cpp

build/obj/release/GeneralStore.o: src/general_store/GeneralStore.cpp src/general_store/GeneralStore.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/GeneralStore.o src/general_store/GeneralStore.cpp

build/obj/release/MorgueDialog.o: src/morgue_dialog/MorgueDialog.cpp src/morgue_dialog/MorgueDialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/MorgueDialog.o src/morgue_dialog/MorgueDialog.cpp

build/obj/release/SeerDialog.o: src/seer_dialog/SeerDialog.cpp src/seer_dialog/SeerDialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/SeerDialog.o src/seer_dialog/SeerDialog.cpp

build/obj/release/ConfinementDialog.o: src/confinement_dialog/ConfinementDialog.cpp src/confinement_dialog/ConfinementDialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/ConfinementDialog.o src/confinement_dialog/ConfinementDialog.cpp

build/obj/release/BankDialog.o: src/bank_dialog/BankDialog.cpp src/bank_dialog/BankDialog.h \
		GameStateManager.h \
		character.h \
		src/bank_dialog/TradeDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/BankDialog.o src/bank_dialog/BankDialog.cpp

build/obj/release/RaceData.o: src/race_data/RaceData.cpp src/race_data/RaceData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/RaceData.o src/race_data/RaceData.cpp

build/obj/release/inventorydialog.o: src/inventory_dialog/inventorydialog.cpp src/inventory_dialog/inventorydialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/inventorydialog.o src/inventory_dialog/inventorydialog.cpp

build/obj/release/optionsdialog.o: src/options_dialog/optionsdialog.cpp src/options_dialog/optionsdialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/optionsdialog.o src/options_dialog/optionsdialog.cpp

build/obj/release/DungeonDialog.o: src/dungeon_dialog/DungeonDialog.cpp src/character_dialog/CharacterDialog.h \
		GameStateManager.h \
		character.h \
		src/dungeon_dialog/DungeonDialog.h \
		src/inventory_dialog/inventorydialog.h \
		src/partyinfo_dialog/partyinfodialog.h \
		src/event/EventManager.h \
		src/dungeon_dialog/MiniMapDialog.h \
		src/dungeon_dialog/DungeonHandlers.h \
		src/spell_casting/SpellCastingDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/DungeonDialog.o src/dungeon_dialog/DungeonDialog.cpp

build/obj/release/partyinfodialog.o: src/partyinfo_dialog/partyinfodialog.cpp src/partyinfo_dialog/partyinfodialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/partyinfodialog.o src/partyinfo_dialog/partyinfodialog.cpp

build/obj/release/dungeonmap.o: src/dungeonmap/dungeonmap.cpp src/dungeonmap/dungeonmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/dungeonmap.o src/dungeonmap/dungeonmap.cpp

build/obj/release/TradeDialog.o: src/bank_dialog/TradeDialog.cpp src/bank_dialog/TradeDialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/TradeDialog.o src/bank_dialog/TradeDialog.cpp

build/obj/release/game_resources.o: src/game_resources.cpp include/game_resources.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/game_resources.o src/game_resources.cpp

build/obj/release/DungeonMinimap.o: src/dungeon_dialog/DungeonMinimap.cpp src/dungeon_dialog/DungeonDialog.h \
		src/inventory_dialog/inventorydialog.h \
		GameStateManager.h \
		character.h \
		src/partyinfo_dialog/partyinfodialog.h \
		src/event/EventManager.h \
		src/dungeon_dialog/MiniMapDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/DungeonMinimap.o src/dungeon_dialog/DungeonMinimap.cpp

build/obj/release/DungeonHandlers.o: src/dungeon_dialog/DungeonHandlers.cpp src/dungeon_dialog/DungeonHandlers.h \
		src/dungeon_dialog/DungeonDialog.h \
		src/inventory_dialog/inventorydialog.h \
		GameStateManager.h \
		character.h \
		src/partyinfo_dialog/partyinfodialog.h \
		src/event/EventManager.h \
		src/dungeon_dialog/MiniMapDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/DungeonHandlers.o src/dungeon_dialog/DungeonHandlers.cpp

build/obj/release/EventManager.o: src/event/EventManager.cpp src/event/EventManager.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/EventManager.o src/event/EventManager.cpp

build/obj/release/UpdateManager.o: src/update/UpdateManager.cpp src/update/UpdateManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/UpdateManager.o src/update/UpdateManager.cpp

build/obj/release/UpdateDialog.o: src/update/UpdateDialog.cpp src/update/UpdateDialog.h \
		src/update/UpdateManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/UpdateDialog.o src/update/UpdateDialog.cpp

build/obj/release/SpellCastingDialog.o: src/spell_casting/SpellCastingDialog.cpp src/spell_casting/SpellCastingDialog.h \
		GameStateManager.h \
		character.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/SpellCastingDialog.o src/spell_casting/SpellCastingDialog.cpp

build/obj/release/moc_GameStateManager.o: build/moc/moc_GameStateManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_GameStateManager.o build/moc/moc_GameStateManager.cpp

build/obj/release/moc_game_menu.o: build/moc/moc_game_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_game_menu.o build/moc/moc_game_menu.cpp

build/obj/release/moc_TheCity.o: build/moc/moc_TheCity.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_TheCity.o build/moc/moc_TheCity.cpp

build/obj/release/moc_StoryDialog.o: build/moc/moc_StoryDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_StoryDialog.o build/moc/moc_StoryDialog.cpp

build/obj/release/moc_MonsterEditorDialog.o: build/moc/moc_MonsterEditorDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_MonsterEditorDialog.o build/moc/moc_MonsterEditorDialog.cpp

build/obj/release/moc_SpellbookEditorDialog.o: build/moc/moc_SpellbookEditorDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_SpellbookEditorDialog.o build/moc/moc_SpellbookEditorDialog.cpp

build/obj/release/moc_NetworkManager.o: build/moc/moc_NetworkManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_NetworkManager.o build/moc/moc_NetworkManager.cpp

build/obj/release/moc_hallofrecordsdialog.o: build/moc/moc_hallofrecordsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_hallofrecordsdialog.o build/moc/moc_hallofrecordsdialog.cpp

build/obj/release/moc_createcharacterdialog.o: build/moc/moc_createcharacterdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_createcharacterdialog.o build/moc/moc_createcharacterdialog.cpp

build/obj/release/moc_AboutDialog.o: build/moc/moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_AboutDialog.o build/moc/moc_AboutDialog.cpp

build/obj/release/moc_CharacterDialog.o: build/moc/moc_CharacterDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_CharacterDialog.o build/moc/moc_CharacterDialog.cpp

build/obj/release/moc_MessageWindow.o: build/moc/moc_MessageWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_MessageWindow.o build/moc/moc_MessageWindow.cpp

build/obj/release/moc_SenderWindow.o: build/moc/moc_SenderWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_SenderWindow.o build/moc/moc_SenderWindow.cpp

build/obj/release/moc_library_dialog.o: build/moc/moc_library_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_library_dialog.o build/moc/moc_library_dialog.cpp

build/obj/release/moc_automap_dialog.o: build/moc/moc_automap_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_automap_dialog.o build/moc/moc_automap_dialog.cpp

build/obj/release/moc_game_controller.o: build/moc/moc_game_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_game_controller.o build/moc/moc_game_controller.cpp

build/obj/release/moc_characterlistdialog.o: build/moc/moc_characterlistdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_characterlistdialog.o build/moc/moc_characterlistdialog.cpp

build/obj/release/moc_helplesson.o: build/moc/moc_helplesson.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_helplesson.o build/moc/moc_helplesson.cpp

build/obj/release/moc_mordorstatistics.o: build/moc/moc_mordorstatistics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_mordorstatistics.o build/moc/moc_mordorstatistics.cpp

build/obj/release/moc_LoadingScreen.o: build/moc/moc_LoadingScreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_LoadingScreen.o build/moc/moc_LoadingScreen.cpp

build/obj/release/moc_GuildsDialog.o: build/moc/moc_GuildsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_GuildsDialog.o build/moc/moc_GuildsDialog.cpp

build/obj/release/moc_GeneralStore.o: build/moc/moc_GeneralStore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_GeneralStore.o build/moc/moc_GeneralStore.cpp

build/obj/release/moc_MorgueDialog.o: build/moc/moc_MorgueDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_MorgueDialog.o build/moc/moc_MorgueDialog.cpp

build/obj/release/moc_SeerDialog.o: build/moc/moc_SeerDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_SeerDialog.o build/moc/moc_SeerDialog.cpp

build/obj/release/moc_ConfinementDialog.o: build/moc/moc_ConfinementDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_ConfinementDialog.o build/moc/moc_ConfinementDialog.cpp

build/obj/release/moc_BankDialog.o: build/moc/moc_BankDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_BankDialog.o build/moc/moc_BankDialog.cpp

build/obj/release/moc_inventorydialog.o: build/moc/moc_inventorydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_inventorydialog.o build/moc/moc_inventorydialog.cpp

build/obj/release/moc_optionsdialog.o: build/moc/moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_optionsdialog.o build/moc/moc_optionsdialog.cpp

build/obj/release/moc_DungeonDialog.o: build/moc/moc_DungeonDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_DungeonDialog.o build/moc/moc_DungeonDialog.cpp

build/obj/release/moc_partyinfodialog.o: build/moc/moc_partyinfodialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_partyinfodialog.o build/moc/moc_partyinfodialog.cpp

build/obj/release/moc_dungeonmap.o: build/moc/moc_dungeonmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_dungeonmap.o build/moc/moc_dungeonmap.cpp

build/obj/release/moc_TradeDialog.o: build/moc/moc_TradeDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_TradeDialog.o build/moc/moc_TradeDialog.cpp

build/obj/release/moc_EventManager.o: build/moc/moc_EventManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_EventManager.o build/moc/moc_EventManager.cpp

build/obj/release/moc_MiniMapDialog.o: build/moc/moc_MiniMapDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_MiniMapDialog.o build/moc/moc_MiniMapDialog.cpp

build/obj/release/moc_UpdateManager.o: build/moc/moc_UpdateManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_UpdateManager.o build/moc/moc_UpdateManager.cpp

build/obj/release/moc_UpdateDialog.o: build/moc/moc_UpdateDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_UpdateDialog.o build/moc/moc_UpdateDialog.cpp

build/obj/release/moc_SpellCastingDialog.o: build/moc/moc_SpellCastingDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/release/moc_SpellCastingDialog.o build/moc/moc_SpellCastingDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

